oauth-db:
 image: mysql:5.7.9
 environment:
  - MYSQL_ROOT_PASSWORD=changeIt2016
 restart: always
 volumes:
  - "./data/mysql:/var/lib/mysql"
 entrypoint: 
  - /entrypoint.sh 
  - --character-set-server=utf8
  - --collation-server=utf8_general_ci
oauth-main:
 build: .
 links:
  - oauth-db:db
 ports:
  - "8080:8080"
 restart: always
 volumes: 
  - "./data/images:/app/images"
